# Generated by Django 2.1.3 on 2019-02-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainmood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
