# Generated by Django 2.1.3 on 2019-02-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainmood', '0003_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='parent_mood',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.AddField(
            model_name='mood',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
