# Generated by Django 2.1.3 on 2019-03-05 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maintainmood', '0004_auto_20190221_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 5, 4, 42, 7, 301617, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
