# Generated by Django 2.1.3 on 2019-03-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainmood', '0005_mood_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
