# Generated by Django 2.1.3 on 2019-03-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainmood', '0006_auto_20190305_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='time_posted',
            field=models.TextField(blank=True),
        ),
    ]
